apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-nomduclient-nomduprojet-frontend-cert
  namespace: staging-nomduclient-nomduprojet-frontend
spec:
  secretName: staging-nomduclient-nomduprojet-frontend-tls
  dnsNames:
    - staging.example.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
