apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: staging-nomduclient-nomduprojet-frontend-hpa
  namespace: staging-nomduclient-nomduprojet-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staging-nomduclient-nomduprojet-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
