apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-customerName-projectName-frontend-cert
  namespace: prod-customerName-projectName-frontend
spec:
  secretName: prod-customerName-projectName-frontend-tls
  dnsNames:
    - example.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
