apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-nomduclient-nomduprojet-frontend-cert
  namespace: prod-nomduclient-nomduprojet-frontend
spec:
  secretName: prod-nomduclient-nomduprojet-frontend-tls
  dnsNames:
    - example.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
