apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-customerName-projectName-frontend-hpa
  namespace: prod-customerName-projectName-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-customerName-projectName-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
