apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-nomduclient-nomduprojet-frontend-hpa
  namespace: prod-nomduclient-nomduprojet-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-nomduclient-nomduprojet-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
